const mongoose = require("mongoose");
const dotenv = require("dotenv");
const { connectDB } = require("./config/db");
const { Lobby } = require("./models/Lobby");
const { Game } = require("./models/Game");

dotenv.config();

const MONGO_URI =
  process.env.MONGO_URI || "mongodb://127.0.0.1:27017/hacknohu";

async function seed() {
  try {
    await connectDB(MONGO_URI);
    console.log("Connected to MongoDB");

    // Clear existing data
    await Game.deleteMany({});
    await Lobby.deleteMany({});
    console.log("Cleared existing data");

    // Create Lobbies (14+ lobbies như hacknohu79.com)
    const lobbies = await Lobby.insertMany([
      { name: "T1 Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "NS Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "MW Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "YB Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "Askme Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "RTG Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "EvoPlay Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "Live22 Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "GP Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "YGR Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "Hacksaw Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "168G Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "ILOVEU Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "5G Điện Tử", image_url: "https://hacknohu79.com/assets/background.gif" },
      // Giữ lại 3 lobby cũ để tương thích
      { name: "Hot Games", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "New Games", image_url: "https://hacknohu79.com/assets/background.gif" },
      { name: "Popular Games", image_url: "https://hacknohu79.com/assets/background.gif" },
    ]);

    const lobby1 = lobbies.find(l => l.name === "Hot Games") || lobbies[0];
    const lobby2 = lobbies.find(l => l.name === "New Games") || lobbies[1];
    const lobby3 = lobbies.find(l => l.name === "Popular Games") || lobbies[2];
    const lobby4 = lobbies.find(l => l.name === "T1 Điện Tử") || lobbies[3];
    const lobby5 = lobbies.find(l => l.name === "NS Điện Tử") || lobbies[4];
    const lobby6 = lobbies.find(l => l.name === "MW Điện Tử") || lobbies[5];
    const lobby7 = lobbies.find(l => l.name === "YB Điện Tử") || lobbies[6];
    const lobby8 = lobbies.find(l => l.name === "Askme Điện Tử") || lobbies[7];
    const lobby9 = lobbies.find(l => l.name === "RTG Điện Tử") || lobbies[8];
    const lobby10 = lobbies.find(l => l.name === "EvoPlay Điện Tử") || lobbies[9];

    console.log(`Created ${lobbies.length} lobbies`);

    // Create Games
    const games = [
      {
        name: "Dragon's Return",
        vietnamese_name: "Rồng Trở Lại",
        image_url: "https://hacknohu79.com/assets/long-sinh-2.png",
        label: "DRAGONS RETURNED",
        label_color: "purple",
        win_rate: 95,
        lobby: lobby1._id,
      },
      {
        name: "Fortune Ox",
        vietnamese_name: "Trâu Vàng",
        image_url: "https://hacknohu79.com/assets/trau-vang.png",
        label: "10,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby1._id,
      },
      {
        name: "Gates of Olympus",
        vietnamese_name: "Cổng Olympus",
        image_url: "https://hacknohu79.com/assets/canh-cua-iguazu.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 92,
        lobby: lobby1._id,
      },
      {
        name: "Sweet Bonanza",
        vietnamese_name: "Kẹo Ngọt",
        image_url: "https://hacknohu79.com/assets/keo-thach.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 90,
        lobby: lobby1._id,
      },
      {
        name: "Starlight Princess",
        vietnamese_name: "Công Chúa Ánh Sao",
        image_url: "https://hacknohu79.com/assets/cong-chua-joker.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 87,
        lobby: lobby1._id,
      },
      {
        name: "Sugar Rush",
        vietnamese_name: "Đường Ngọt",
        image_url: "https://hacknohu79.com/assets/sugar-boom.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 89,
        lobby: lobby1._id,
      },
      {
        name: "Wild West Gold",
        vietnamese_name: "Miền Tây Hoang Dã",
        image_url: "https://hacknohu79.com/assets/cao-boi-mien-tay.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 85,
        lobby: lobby1._id,
      },
      {
        name: "The Dog House",
        vietnamese_name: "Ngôi Nhà Chó",
        image_url: "https://hacknohu79.com/assets/chu-cho-may-man.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 91,
        lobby: lobby1._id,
      },
      {
        name: "Big Bass Bonanza",
        vietnamese_name: "Cá Lớn",
        image_url: "https://hacknohu79.com/assets/big-bass-bonanza-1000.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 86,
        lobby: lobby2._id,
      },
      {
        name: "Fire Strike",
        vietnamese_name: "Lửa Cháy",
        image_url: "https://hacknohu79.com/assets/ngon-lua-sieu-cap.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 84,
        lobby: lobby2._id,
      },
      {
        name: "Aztec Gems",
        vietnamese_name: "Đá Quý Aztec",
        image_url: "https://hacknohu79.com/assets/kho-bau-aztec.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby2._id,
      },
      {
        name: "Mahjong Ways",
        vietnamese_name: "Mahjong",
        image_url: "https://hacknohu79.com/assets/duong-mat-chuoc.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 90,
        lobby: lobby2._id,
      },
      {
        name: "Lucky Neko",
        vietnamese_name: "Mèo May Mắn",
        image_url: "https://hacknohu79.com/assets/neko-may-man.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby3._id,
      },
      {
        name: "Piggy Bankers",
        vietnamese_name: "Heo Tiết Kiệm",
        image_url: "https://hacknohu79.com/assets/ba-chu-heo-dien.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 89,
        lobby: lobby3._id,
      },
      {
        name: "Caishen Wins",
        vietnamese_name: "Thần Tài",
        image_url: "https://hacknohu79.com/assets/chien-thang-cai-shen.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 93,
        lobby: lobby3._id,
      },
      {
        name: "5 Lions Megaways",
        vietnamese_name: "5 Sư Tử",
        image_url: "https://hacknohu79.com/assets/5-su-tu-tai-sinh.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 86,
        lobby: lobby3._id,
      },
      {
        name: "777",
        vietnamese_name: "777",
        image_url: "https://hacknohu79.com/assets/777.png",
        label: "JACKPOT",
        label_color: "red",
        win_rate: 92,
        lobby: lobby1._id,
      },
      {
        name: "Mahjong Ways 2",
        vietnamese_name: "Đường Mạt Chược 2",
        image_url: "https://hacknohu79.com/assets/duong-mat-chuoc-2.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 91,
        lobby: lobby1._id,
      },
      {
        name: "Aztec Treasure",
        vietnamese_name: "Kho Báu Aztec",
        image_url: "https://hacknohu79.com/assets/kho-bau-aztec.png",
        label: "10,000x",
        label_color: "red",
        win_rate: 89,
        lobby: lobby1._id,
      },
      {
        name: "Lucky Rabbit",
        vietnamese_name: "Thỏ May Mắn",
        image_url: "https://hacknohu79.com/assets/tho-may-man.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 88,
        lobby: lobby2._id,
      },
      {
        name: "Wild Bandits",
        vietnamese_name: "Wild Đạo Tặc",
        image_url: "https://hacknohu79.com/assets/wild-dao-tac.png",
        label: "WILD",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby2._id,
      },
      {
        name: "Unicorn Guide",
        vietnamese_name: "Kỳ Lân Mách Nước",
        image_url: "https://hacknohu79.com/assets/ky-lan-mach-nuoc.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 90,
        lobby: lobby2._id,
      },
      {
        name: "Drunk Lady",
        vietnamese_name: "Quý bà say rượu",
        image_url: "https://hacknohu79.com/assets/quy-ba-say-ruou.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 85,
        lobby: lobby2._id,
      },
      {
        name: "Cai Shen Victory",
        vietnamese_name: "Chiến Thắng Cai Shen",
        image_url: "https://hacknohu79.com/assets/chien-thang-cai-shen.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 94,
        lobby: lobby3._id,
      },
      {
        name: "Treasure Adventure",
        vietnamese_name: "Cuộc phiêu lưu kho báu",
        image_url: "https://hacknohu79.com/assets/cuoc-phieu-luu-kho-bau.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 88,
        lobby: lobby3._id,
      },
      {
        name: "Inca Wonder",
        vietnamese_name: "Kỳ Quan Inca",
        image_url: "https://hacknohu79.com/assets/ky-quan-inca.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 91,
        lobby: lobby3._id,
      },
      {
        name: "Golden Snake",
        vietnamese_name: "Rắn vàng chiếu ái",
        image_url: "https://hacknohu79.com/assets/ran-vang-chieu-ai.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 89,
        lobby: lobby1._id,
      },
      {
        name: "Yakuza Honor",
        vietnamese_name: "Yakuza Honor",
        image_url: "https://hacknohu79.com/assets/yakuza-honor.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby2._id,
      },
      {
        name: "Geisha Revenge",
        vietnamese_name: "Geisha's Revenge",
        image_url: "https://hacknohu79.com/assets/geishas-revenge.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 90,
        lobby: lobby2._id,
      },
      {
        name: "Premium Chocolate",
        vietnamese_name: "Sôcôla Cao Cấp",
        image_url: "https://hacknohu79.com/assets/socola-cao-cap.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 86,
        lobby: lobby3._id,
      },
      {
        name: "Fantasia Wave",
        vietnamese_name: "Sóng Fantasia",
        image_url: "https://hacknohu79.com/assets/song-fantasia.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby3._id,
      },
      // Thêm 69 games nữa để đạt 100 games
      {
        name: "Museum Mystery",
        vietnamese_name: "Museum Mystery",
        image_url: "https://hacknohu79.com/assets/museum-mystery.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby4._id,
      },
      {
        name: "Oishi Delights",
        vietnamese_name: "Oishi Delights",
        image_url: "https://hacknohu79.com/assets/oishi-delights.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 89,
        lobby: lobby4._id,
      },
      {
        name: "Crazy Pigs",
        vietnamese_name: "Ba chú heo điên",
        image_url: "https://hacknohu79.com/assets/ba-chu-heo-dien.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 86,
        lobby: lobby4._id,
      },
      {
        name: "Iguazu Gates",
        vietnamese_name: "Cánh Cửa Iguazu",
        image_url: "https://hacknohu79.com/assets/canh-cua-iguazu.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 91,
        lobby: lobby4._id,
      },
      {
        name: "Shark Hunter",
        vietnamese_name: "Thợ Săn Cá Mập",
        image_url: "https://hacknohu79.com/assets/tho-san-ca-map.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby5._id,
      },
      {
        name: "Football Fever",
        vietnamese_name: "Sức nóng bóng đá",
        image_url: "https://hacknohu79.com/assets/suc-nong-bong-da.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 85,
        lobby: lobby5._id,
      },
      {
        name: "Chicken Race",
        vietnamese_name: "Cuộc Đua Gà Con",
        image_url: "https://hacknohu79.com/assets/cuoc-dua-ga-con.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby5._id,
      },
      {
        name: "Zombie Apocalypse",
        vietnamese_name: "Đại Dịch Xác Sống",
        image_url: "https://hacknohu79.com/assets/dai-dich-xac-song.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 90,
        lobby: lobby5._id,
      },
      {
        name: "Anubis Wrath",
        vietnamese_name: "Cơn Thịnh Nộ Của Anubis",
        image_url: "https://hacknohu79.com/assets/con-thinh-no-cua-anubis.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby6._id,
      },
      {
        name: "Mystic Poison",
        vietnamese_name: "Độc Dược Thần Bí",
        image_url: "https://hacknohu79.com/assets/doc-duoc-than-bi.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 86,
        lobby: lobby6._id,
      },
      {
        name: "Pinata Wins",
        vietnamese_name: "Pinata Wins",
        image_url: "https://hacknohu79.com/assets/pinata-wins.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby6._id,
      },
      {
        name: "Wild Ape",
        vietnamese_name: "Wild Ape #3258",
        image_url: "https://hacknohu79.com/assets/wild-ape-3258.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby6._id,
      },
      {
        name: "Cash Mania",
        vietnamese_name: "Cash Mania",
        image_url: "https://hacknohu79.com/assets/cash-mania.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 91,
        lobby: lobby7._id,
      },
      {
        name: "Gems and Gold",
        vietnamese_name: "Đá Quý Và Vàng",
        image_url: "https://hacknohu79.com/assets/da-quy-va-vang.png",
        label: "10,000x",
        label_color: "red",
        win_rate: 89,
        lobby: lobby7._id,
      },
      {
        name: "Lucky Dragon",
        vietnamese_name: "Chú Rồng May Mắn",
        image_url: "https://hacknohu79.com/assets/chu-rong-may-man.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 88,
        lobby: lobby7._id,
      },
      {
        name: "Dragon Return 2",
        vietnamese_name: "Long Sinh 2",
        image_url: "https://hacknohu79.com/assets/long-sinh-2.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 92,
        lobby: lobby7._id,
      },
      {
        name: "Wolf Hunt",
        vietnamese_name: "Cuộc Đi Săn Của Người Sói",
        image_url: "https://hacknohu79.com/assets/cuoc-di-san-cua-nguoi-soi.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 87,
        lobby: lobby8._id,
      },
      {
        name: "Tsar's Treasure",
        vietnamese_name: "Kho Báu Của Sa Hoàng",
        image_url: "https://hacknohu79.com/assets/kho-bau-cua-sa-hoang.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 90,
        lobby: lobby8._id,
      },
      {
        name: "Mafia Gang",
        vietnamese_name: "Băng Nhóm Mafia",
        image_url: "https://hacknohu79.com/assets/bang-nhom-mafia.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 86,
        lobby: lobby8._id,
      },
      {
        name: "Rich Forge",
        vietnamese_name: "Lò Rèn Giàu Có",
        image_url: "https://hacknohu79.com/assets/lo-ren-giau-co.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby8._id,
      },
      {
        name: "Rich Knockdown",
        vietnamese_name: "Giàu Sang Hạ Gục",
        image_url: "https://hacknohu79.com/assets/giau-sang-ha-guc.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby9._id,
      },
      {
        name: "Furious Maiden",
        vietnamese_name: "Thiếu Nữ Cuồng Nộ",
        image_url: "https://hacknohu79.com/assets/thieu-nu-cuong-no.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby9._id,
      },
      {
        name: "Street Graffiti",
        vietnamese_name: "Graffiti Đường Phố",
        image_url: "https://hacknohu79.com/assets/graffiti-duong-pho.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 85,
        lobby: lobby9._id,
      },
      {
        name: "Super Ace",
        vietnamese_name: "Siêu Cấp Ace",
        image_url: "https://hacknohu79.com/assets/sieu-cap-ace.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 91,
        lobby: lobby9._id,
      },
      {
        name: "Golden Empire",
        vietnamese_name: "Đế quốc hoàng kim",
        image_url: "https://hacknohu79.com/assets/de-quoc-hoang-kim-3.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 90,
        lobby: lobby10._id,
      },
      {
        name: "Kala Gem",
        vietnamese_name: "Bảo thạch Kala",
        image_url: "https://hacknohu79.com/assets/bao-thach-kala.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby10._id,
      },
      {
        name: "King of Cards",
        vietnamese_name: "Quyền Vương",
        image_url: "https://hacknohu79.com/assets/quyen-vuong.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby10._id,
      },
      {
        name: "Lucky Gem 2",
        vietnamese_name: "Ngọc may mắn 2",
        image_url: "https://hacknohu79.com/assets/ngoc-may-man-2.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 89,
        lobby: lobby1._id,
      },
      {
        name: "Infinite Cards",
        vietnamese_name: "Vương bài vô hạn",
        image_url: "https://hacknohu79.com/assets/vuong-bai-vo-han.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 86,
        lobby: lobby1._id,
      },
      {
        name: "Crazy 777",
        vietnamese_name: "Điên Cuồng 777",
        image_url: "https://hacknohu79.com/assets/dien-cuong-777.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 92,
        lobby: lobby2._id,
      },
      {
        name: "Crazy Gunner",
        vietnamese_name: "Pháo thủ điên cuồng",
        image_url: "https://hacknohu79.com/assets/phao-thu-dien-cuong.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby2._id,
      },
      {
        name: "Lucky Gem 3",
        vietnamese_name: "Ngọc may mắn 3",
        image_url: "https://hacknohu79.com/assets/ngoc-may-man-3.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 87,
        lobby: lobby2._id,
      },
      {
        name: "Ali Bar",
        vietnamese_name: "Ali quán ba quán ba",
        image_url: "https://hacknohu79.com/assets/ali-quan-ba-quan-ba.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby3._id,
      },
      {
        name: "JILI Fortune Zombie",
        vietnamese_name: "JILI FORTUNE ZOMBIE",
        image_url: "https://hacknohu79.com/assets/jili-fortune-zombie.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 86,
        lobby: lobby3._id,
      },
      {
        name: "3 Lucky Lions",
        vietnamese_name: "3 Sư Tử May Mắn",
        image_url: "https://hacknohu79.com/assets/3-su-tu-may-man.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 90,
        lobby: lobby3._id,
      },
      {
        name: "3 Treasure Coins 2",
        vietnamese_name: "3 kho báu đồng xu 2",
        image_url: "https://hacknohu79.com/assets/3-kho-bau-dong-xu-2.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 88,
        lobby: lobby4._id,
      },
      {
        name: "Super Ace II",
        vietnamese_name: "Siêu Ách II",
        image_url: "https://hacknohu79.com/assets/sieu-ach-ii.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby4._id,
      },
      {
        name: "3 Electric Bulls",
        vietnamese_name: "3 Trâu Tích Điện",
        image_url: "https://hacknohu79.com/assets/3-trau-tich-dien.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 91,
        lobby: lobby4._id,
      },
      {
        name: "Lucky Coin",
        vietnamese_name: "Đồng xu may mắn",
        image_url: "https://hacknohu79.com/assets/dong-xu-may-man.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby5._id,
      },
      {
        name: "Super Joker Ace",
        vietnamese_name: "Siêu Át Joker",
        image_url: "https://hacknohu79.com/assets/sieu-at-joker.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby5._id,
      },
      {
        name: "Rich Pigs",
        vietnamese_name: "Ba chú heo giàu có",
        image_url: "https://hacknohu79.com/assets/ba-chu-heo-giau-co.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 86,
        lobby: lobby5._id,
      },
      {
        name: "Roma X Premium",
        vietnamese_name: "Roma X Cao Cấp",
        image_url: "https://hacknohu79.com/assets/roma-x-cao-cap.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 90,
        lobby: lobby6._id,
      },
      {
        name: "Sweet Magic",
        vietnamese_name: "Ma Thuật Ngọt Ngào",
        image_url: "https://hacknohu79.com/assets/ma-thuat-ngot-ngao.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby6._id,
      },
      {
        name: "3 Wild Coins",
        vietnamese_name: "3 Đồng Xu Ngựa Hoang",
        image_url: "https://hacknohu79.com/assets/3-dong-xu-ngua-hoang.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 89,
        lobby: lobby6._id,
      },
      {
        name: "Coin Tree",
        vietnamese_name: "Coin Tree",
        image_url: "https://hacknohu79.com/assets/coin-tree.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 88,
        lobby: lobby7._id,
      },
      {
        name: "Treasure Quest",
        vietnamese_name: "Nhiệm vụ tìm kho báu",
        image_url: "https://hacknohu79.com/assets/nhiem-vu-tim-kho-bau.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 91,
        lobby: lobby7._id,
      },
      {
        name: "Safari Mystery",
        vietnamese_name: "Bí Ẩn Safari",
        image_url: "https://hacknohu79.com/assets/bi-an-safari.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 87,
        lobby: lobby7._id,
      },
      {
        name: "Fruit Wheel",
        vietnamese_name: "Vòng quay trái cây",
        image_url: "https://hacknohu79.com/assets/vong-quay-trai-cay.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby8._id,
      },
      {
        name: "Pirate Queen 2",
        vietnamese_name: "Nữ Hoàng Hải Tặc 2",
        image_url: "https://hacknohu79.com/assets/nu-hoang-hai-tac-2.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby8._id,
      },
      {
        name: "Golden Bank 2",
        vietnamese_name: "Ngân Hàng Vàng 2",
        image_url: "https://hacknohu79.com/assets/ngan-hang-vang-2.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 90,
        lobby: lobby8._id,
      },
      {
        name: "Lucky Dog",
        vietnamese_name: "Chú chó may mắn",
        image_url: "https://hacknohu79.com/assets/chu-cho-may-man.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby9._id,
      },
      {
        name: "Lucky Leopard",
        vietnamese_name: "Báo Đốm May Mắn",
        image_url: "https://hacknohu79.com/assets/bao-dom-may-man.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 89,
        lobby: lobby9._id,
      },
      {
        name: "Shogun",
        vietnamese_name: "Shogun",
        image_url: "https://hacknohu79.com/assets/shogun.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 91,
        lobby: lobby9._id,
      },
      {
        name: "Roman Warrior",
        vietnamese_name: "Nữ Chiến Binh La Mã",
        image_url: "https://hacknohu79.com/assets/nu-chien-binh-la-ma.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 88,
        lobby: lobby10._id,
      },
      {
        name: "Inca Legend",
        vietnamese_name: "Huyền thoại Inca",
        image_url: "https://hacknohu79.com/assets/huyen-thoai-inca.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby10._id,
      },
      {
        name: "Dragon Firework",
        vietnamese_name: "Pháo Rồng Tài Lộc",
        image_url: "https://hacknohu79.com/assets/phao-rong-tai-loc.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 90,
        lobby: lobby1._id,
      },
      {
        name: "New Year Fortune",
        vietnamese_name: "Năm Mới Lộ Lộ Phát",
        image_url: "https://hacknohu79.com/assets/nam-moi-lo-lo-phat.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby1._id,
      },
      {
        name: "Veda Goddess",
        vietnamese_name: "Nữ Thần Vẻ Đa",
        image_url: "https://hacknohu79.com/assets/nu-than-ve-da.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby2._id,
      },
      {
        name: "Ultimate Illusion",
        vietnamese_name: "Ảo Bại Tối Cao",
        image_url: "https://hacknohu79.com/assets/ao-bai-toi-cao.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 87,
        lobby: lobby2._id,
      },
      {
        name: "Flying Fortune God",
        vietnamese_name: "Thần Tài Phi Dương",
        image_url: "https://hacknohu79.com/assets/than-tai-phi-dương.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 91,
        lobby: lobby2._id,
      },
      {
        name: "Egyptian Treasure",
        vietnamese_name: "Kho báu Ai Cập",
        image_url: "https://hacknohu79.com/assets/kho-bau-ai-cap.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 89,
        lobby: lobby3._id,
      },
      {
        name: "Elemental Surge",
        vietnamese_name: "Nguyên Tố Dâng Trào",
        image_url: "https://hacknohu79.com/assets/nguyen-to-dang-trao.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby3._id,
      },
      {
        name: "Golden Leopard",
        vietnamese_name: "Báo Vàng",
        image_url: "https://hacknohu79.com/assets/bao-vang.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby3._id,
      },
      {
        name: "Magic Merge",
        vietnamese_name: "Ma Thuật Ghép",
        image_url: "https://hacknohu79.com/assets/ma-thuat-ghep.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 90,
        lobby: lobby4._id,
      },
      {
        name: "Big Sea Storm",
        vietnamese_name: "Tầm Bão Biển Lớn",
        image_url: "https://hacknohu79.com/assets/tam-bao-bien-lon.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 89,
        lobby: lobby4._id,
      },
      {
        name: "FC Fish Battle",
        vietnamese_name: "FC Cuộc Chiến Bắn Cá",
        image_url: "https://hacknohu79.com/assets/fc-cuoc-chien-ban-ca.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 88,
        lobby: lobby4._id,
      },
      {
        name: "CHILIHUAHUA",
        vietnamese_name: "CHILIHUAHUA",
        image_url: "https://hacknohu79.com/assets/chilihuahua.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby5._id,
      },
      {
        name: "Western Cowboy",
        vietnamese_name: "Cao Bồi Miền Tây",
        image_url: "https://hacknohu79.com/assets/cao-boi-mien-tay.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 91,
        lobby: lobby5._id,
      },
      {
        name: "Honey Strike 2",
        vietnamese_name: "Bạo Kích Đường Mật 2",
        image_url: "https://hacknohu79.com/assets/bao-kich-duong-mat-2.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby5._id,
      },
      {
        name: "Fortune Punch",
        vietnamese_name: "Cú Đấm Tài Lộc",
        image_url: "https://hacknohu79.com/assets/cu-dam-tai-loc.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby6._id,
      },
      {
        name: "Inca Queen",
        vietnamese_name: "Nữ Hoàng Inca",
        image_url: "https://hacknohu79.com/assets/nu-hoang-inca.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 87,
        lobby: lobby6._id,
      },
      {
        name: "Treasure Swap 3x3",
        vietnamese_name: "Của Cải Đổi Đảo 3x3",
        image_url: "https://hacknohu79.com/assets/cua-cai-doi-dao-3x3.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby6._id,
      },
      {
        name: "Tower Climber",
        vietnamese_name: "Cao thủ trèo tháp",
        image_url: "https://hacknohu79.com/assets/cao-thu-treo-thap.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby7._id,
      },
      {
        name: "Mine Sweeper",
        vietnamese_name: "Cao thủ quét mìn",
        image_url: "https://hacknohu79.com/assets/cao-thu-quet-min.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 87,
        lobby: lobby7._id,
      },
      {
        name: "FC Gods Fortune",
        vietnamese_name: "FC Chúng Thần Phát Tài",
        image_url: "https://hacknohu79.com/assets/fc-chung-than-phat-tai.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 91,
        lobby: lobby7._id,
      },
      {
        name: "Money Direction",
        vietnamese_name: "Hướng về tiền",
        image_url: "https://hacknohu79.com/assets/huong-ve-tien.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 89,
        lobby: lobby8._id,
      },
      {
        name: "Night Market 2",
        vietnamese_name: "Chợ Đêm 2",
        image_url: "https://hacknohu79.com/assets/cho-dem-2.png",
        label: "5,000x",
        label_color: "red",
        win_rate: 88,
        lobby: lobby8._id,
      },
      {
        name: "Golden Egg",
        vietnamese_name: "Trứng Vàng",
        image_url: "https://hacknohu79.com/assets/trung-vang.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 90,
        lobby: lobby8._id,
      },
      {
        name: "Treasure Cat",
        vietnamese_name: "Mèo Tài Tầm Bảo",
        image_url: "https://hacknohu79.com/assets/meo-tai-tam-bao.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 87,
        lobby: lobby9._id,
      },
      {
        name: "Zeus God",
        vietnamese_name: "Thần Zeus",
        image_url: "https://hacknohu79.com/assets/than-zeus-2.png",
        label: "8,000x",
        label_color: "red",
        win_rate: 92,
        lobby: lobby9._id,
      },
      {
        name: "Olympus Victory",
        vietnamese_name: "Chiến Thắng Olympus",
        image_url: "https://hacknohu79.com/assets/chien-thang-olympus.png",
        label: "BONUS",
        label_color: "purple",
        win_rate: 89,
        lobby: lobby9._id,
      },
      {
        name: "Hades Gate",
        vietnamese_name: "Cánh Cổng Hades",
        image_url: "https://hacknohu79.com/assets/canh-cong-hades.png",
        label: "MULTIPLIERS",
        label_color: "orange",
        win_rate: 88,
        lobby: lobby10._id,
      },
      {
        name: "Majestic Express",
        vietnamese_name: "Majestic Express - Cuộc Đua Vàng",
        image_url: "https://hacknohu79.com/assets/majestic-express-cuoc-dua-vang.png",
        label: "6,000x",
        label_color: "red",
        win_rate: 90,
        lobby: lobby10._id,
      },
      {
        name: "Mahjong Wins Super",
        vietnamese_name: "Mahjong Wins Super Scatter",
        image_url: "https://hacknohu79.com/assets/mahjong-wins-super-scatter.png",
        label: "BONUS BUY",
        label_color: "purple",
        win_rate: 87,
        lobby: lobby10._id,
      },
    ];

    await Game.insertMany(games);
    console.log(`Created ${games.length} games`);

    console.log("✅ Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seed();

